### PR TITLE
Update Readme and added ipynb file

### LINKED ISSUE #5: Train the model using new data created in issue #4
- [ ] Train the model using the new dataset as created in issue #4

- [ ] Compare the model performance, assess the generated images' quality using the stipulated measures (code available in the notebook) and document the same in readme of the PR

- [ ] Update repository readme with the quantitative comparison info of these two models

### PR DESCRIPTION
**Pull request by Preetesh21**
Fixes #5 

Update Readme and added ipynb file for the issue #5

### CODE REVIEW

**Review by Chintan2108 — APPROVED** [review]
@Preetesh21 Great work! 
Good inferences on the epoch vs error graphs.

**Review by Chintan2108 — CHANGES_REQUESTED** [review]
Could you add a comparison of the previous model and this model?
Plot graphs for epoch vs PSNR, epoch vs PC and epoch vs SSIM for both the methods together, so that we can visually analyze it?

**Comment by Preetesh21** [comment]
Sure.

**Comment by Preetesh21** [comment]
Added the Graphs for the Parameters.

**Comment by Chintan2108** [comment]
Hi @Preetesh21 
Good work on the graphs. We need to compare the performance of the two models.
Please have only these three graphs in the readme:
1. PSNR vs Epoch (single graph)
   a. One curve for validation of earlier model 
   b. One curve for validation of skewed-data model

2. PC vs Epoch (single graph)
   a. One curve for validation of earlier model 
   b. One curve for validation of skewed-data model

3. SSIM vs Epoch (single graph)
   a. One curve for validation of earlier model 
   b. One curve for validation of skewed-data model

This way we can compare the performance of both models for each of the parameters. Since we want to compare their predictive capabilities, we don't need to have the training curve, only the validation curve is required.

**Comment by Preetesh21** [comment]
ok sure.

**Comment by Preetesh21** [comment]
Done the requested changes.

**Review by Chintan2108 — APPROVED** [review]
Great work @Preetesh21

**Comment by Chintan2108** [comment]
give @Preetesh21 25 points

**Pull request merged**
